### ISSUE TITLE
Erreur lors de l'import des données CSV

### ISSUE THREAD

**Issue by oliviermeunier** [sebcriado/Newsletter-Form#12]
![image](https://user-images.githubusercontent.com/5786996/217479281-9339c211-28fd-450d-aedd-84077420f426.png)

**Comment by oliviermeunier** [comment]
Idem quand on accède à la page du formulaire dans le navigateur
![image](https://user-images.githubusercontent.com/5786996/217479395-1ba3a362-747f-49aa-8ba8-868459eef169.png)

**Comment by sebcriado** [comment]
C'est bizarre parce que ça marche de mon côté

<img width="613" alt="Capture d’écran 2023-02-08 à 10 16 25" src="https://user-images.githubusercontent.com/115630440/217487102-5fe7289e-4a72-4eaa-89ef-32950f9257ad.png">
<img width="839" alt="Capture d’écran 2023-02-08 à 10 16 40" src="https://user-images.githubusercontent.com/115630440/217487126-8ce69358-8bb4-415c-890e-63fc7551e39b.png">

**Comment by oliviermeunier** [comment]
C'est OK !
