### ISSUE TITLE
Comment stocker plusieurs intérêts ?

### ISSUE THREAD

**Issue by oliviermeunier** [sebcriado/Newsletter-Form#15]
Lorsque tu ajouteras les cases à cocher sur ton formulaire, l'utilisateur pourra cocher plusieurs cases.
Comment stocker dans la BDD plusieurs relations entre la table **subscribers** et **interests** ?
La structure actuelle ne permet de stocker qu'un seul intérêt.

**Comment by sebcriado** [comment]
J'ai pourtant créer une autre table qui récupère l'id des subscribers et l'id des intérets.

<img width="180" alt="Capture d’écran 2023-02-13 à 10 25 53" src="https://user-images.githubusercontent.com/115630440/218420417-f80a669b-1e06-4fbe-b515-e3bd24212103.png">

**Comment by oliviermeunier** [comment]
Ton fichier d'export SQL ne doit pas être à jour sur ton dépôt alors ;)
